name: ericmourant
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7435
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a3acab'
    - '#141517'
    - '#747c7e'
    - '#e0d1d8'
    - '#fdfeff'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.6870334930717945
  rhythmicContrast: 0.25
purpose: []
